<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>e3b75cbc-59cd-487b-861c-3f19591b54d3</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TourneyPlanner.Application\TourneyPlanner.Application.csproj" />
      <ProjectReference Include="..\TourneyPlanner.Infrastructure\TourneyPlanner.Infrastructure.csproj" />
    </ItemGroup>

</Project>
